[[plugins]]
repo = 'Shougo/dein.vim'

# Toml
[[plugins]]
repo  = 'cespare/vim-toml'

# airline
[[plugins]]
repo = 'vim-airline/vim-airline'

# nerdtree
[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''                                    
    nnoremap <silent> gs :Gstatus<CR><C-w>T                                    
    nnoremap <silent> gps :Gpush<CR>                                    
    nnoremap <silent> gpl :Gpull<CR>                                    
'''    


[[plugins]]
repo = 'glacambre/firenvim'
hook_post_update = '''
    call firenvim#install(0)
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
    vnoremap / :'<,'>TComment<CR>
'''

[[plugins]]
repo = 'neovim/nvim-lspconfig'
hook_add = '''
lua require("lsp_config")
'''

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'
